### ISSUE TITLE
Remove the redundant bin folder

### ISSUE THREAD

**Issue by kushthedude** [kushthedude/To-Do-App#109]
bin folder was accidentally committed which should not reside with the repositories code.

**Comment by SofiaSimas** [comment]
Hello! Can you assigne this to me?

**Comment by SofiaSimas** [comment]
Thank you! I opened the pull request to remove /bin and add it to gitignore

**Comment by 3t8** [comment]
Sorry, I just read the comments now but already did the pull request in the meantime
