### ISSUE TITLE
Create heroku configuration file for the repository

### ISSUE THREAD

**Issue by kushthedude** [kushthedude/To-Do-App#110]
This is a simple application with a React frontend and Django server.

We can leverage hosting the application on Heroku if someone may write the configuration file.

**Comment by lubomirrozhon** [comment]
Can you assign it to me ?

**Comment by SoumyaRanjanNaik** [comment]
Do you want the "Procfile" used by heroku only for Django right ?

**Comment by kushthedude** [comment]
Yes
